### ISSUE TITLE
so it still doesnt install

### ISSUE THREAD

**Issue by kwal559** [Dartvauder/NeuroSandboxWebUI#122]
tried a few months ago, tried again the other day.
whats frustrating is that in windows right at the very end of installing, right when the error occurs, you have the screen refresh and we are told everything installed perfectly.  well it doesn't.  and even though i went as far as recording the error to playback in slow motion, it's just not worth it.. keep wondering why its a ghost town here despite being a very attractive offering.
Ok all you have to change is
*screen refresh*
Everything works, your welcome.

**Comment by Dartvauder** [comment]
> tried a few months ago, tried again the other day.
> whats frustrating is that in windows right at the very end of installing, right when the error occurs, you have the screen refresh and we are told everything installed perfectly.  well it doesn't.  and even though i went as far as recording the error to playback in slow motion, it's just not worth it.. keep wondering why its a ghost town here despite being a very attractive offering.
> Ok all you have to change is
> *screen refresh*
> Everything works, your welcome.

Hello friend! I think I understand what you mean. There is a problem with the torchmcubes library now. I noticed this error and tried to fix it in every possible way. Unfortunately, I couldn't and I have to wait until the library developer fixes it. But in general, the installation goes fine with all the other libraries. I'll try to do what you asked.
