### ISSUE TITLE
LLVM ERROR: Symbol not found: __svml_cosf8_ha

### ISSUE THREAD

**Issue by chronic8000** [Dartvauder/NeuroSandboxWebUI#25]
LLVM ERROR: Symbol not found: __svml_cosf8_ha
C:\NeuroSandboxWebUI\NeuroSandboxWebUI>

**To Reproduce**
1. After install run start.bat
2. Get: LLVM ERROR: Symbol not found: __svml_cosf8_ha

**Expected behavior**
To run as expected

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Latest

**Additional context**
Install went OK but I get that error?

**Comment by Dartvauder** [comment]
Hello. Sorry for not noticing the issue for so long, I was too busy with the new update

Regarding the error, what do you get. Today I will study this issue, but first I want to clarify. What version of Windows and python do you have?

P.S. In general, a global update was released today. I advise you to do a complete reinstallation of the application, maybe it will help too. Thank you for deciding to try my application

**Comment by chronic8000** [comment]
> > LLVM ERROR: Symbol not found: __svml_cosf8_ha C:\NeuroSandboxWebUI\NeuroSandboxWebUI>
> > **To Reproduce** Steps to reproduce the behavior:
> > 
> > 1. After install run start.bat
> > 2. Get: LLVM ERROR: Symbol not found: __svml_cosf8_ha
> > 
> > **Expected behavior** To run as expected
> > **Desktop (please complete the following information):**
> > 
> > * OS: Windows
> > * Browser Chrome
> > * Version Latest
> > 
> > **Additional context** Install went OK but I get that error?
> 
> Hello. Sorry for not noticing the issue for so long, I was too busy with the new update
> 
> Regarding the error, what do you get. Today I will study this issue, but first I want to clarify. What version of Windows and python do you have?
> 
> P.S. In general, a new update was released today. I advise you to do a complete reinstallation of the application, maybe it will help too. Thank you for deciding to try my application

Python 3.10.6 Windows 11

**Comment by Dartvauder** [comment]
Sorry it took me so long to find an answer. Perhaps [this](https://github.com/lmcinnes/umap/issues/702#issuecomment-1002396093) can help you. Neither I nor my friends had such an error no matter how much we tried to cause it. I really hope this helped you. Let me know
