### ISSUE TITLE
💫 [FeatureRequest] add text-to-singing 🎤🎵

### ISSUE THREAD

**Issue by funmolde** [Dartvauder/NeuroSandboxWebUI#272]
### Feature request

Hello 😀,
I'd like to suggest adding a text-to-singing voice synthesis feature.
https://github.com/topics/singing-voice-synthesis
Thank you -_-

**Comment by Dartvauder** [comment]
> ### Feature request
> 
> Hello 😀,
> I'd like to suggest adding a text-to-singing voice synthesis feature.
> https://github.com/topics/singing-voice-synthesis
> Thank you -_-

Hi friend! Thanks for you suggest. I'll study it today/tomorrow and as soon as I do it, I'll let you know. If you're interested, you can help me test this function in the dev branch before releasing it to main and I'll add you as a tester to contributors☺️

**Comment by funmolde** [comment]
> > ### Feature request Demande de fonctionnalité
> > Hello 😀, Bonjour 😀,
> > I'd like to suggest adding a text-to-singing voice synthesis feature.J'aimerais suggérer d'ajouter une fonctionnalité de synthèse vocale texte-chant.
> > https://github.com/topics/singing-voice-synthesis
> > Thank you -_- Merci -_-
> 
> Hi friend! Thanks for you suggest. I'll study it today/tomorrow and as soon as I do it, I'll let you know. If you're interested, you can help me test this function in the dev branch before releasing it to main and I'll add you as a tester to contributors☺️Salut mon ami! Merci pour votre suggestion. Je vais l'étudier aujourd'hui/demain et dès que je l'aurai fait, je vous le ferai savoir. Si vous êtes intéressé, vous pouvez m'aider à tester cette fonction dans la branche dev avant de la publier sur main et je vous ajouterai en tant que testeur aux contributeurs. ☺️

ok 👌 I want to become a contributor tester😀
keep me posted😊

**Comment by Dartvauder** [comment]
> > > ### Feature request Demande de fonctionnalité
> > > Hello 😀, Bonjour 😀,
> > > I'd like to suggest adding a text-to-singing voice synthesis feature.J'aimerais suggérer d'ajouter une fonctionnalité de synthèse vocale texte-chant.
> > > https://github.com/topics/singing-voice-synthesis
> > > Thank you -_- Merci -_-
> > 
> > 
> > Hi friend! Thanks for you suggest. I'll study it today/tomorrow and as soon as I do it, I'll let you know. If you're interested, you can help me test this function in the dev branch before releasing it to main and I'll add you as a tester to contributors☺️Salut mon ami! Merci pour votre suggestion. Je vais l'étudier aujourd'hui/demain et dès que je l'aurai fait, je vous le ferai savoir. Si vous êtes intéressé, vous pouvez m'aider à tester cette fonction dans la branche dev avant de la publier sur main et je vous ajouterai en tant que testeur aux contributeurs. ☺️
> 
> ok 👌 I want to become a contributor tester😀 keep me posted😊

Hello again. Sorry for taking so long to respond to your suggestion. I was busy with important parts of the project and simultaneously studying what you suggested. I think I'll be able to add DiffSinger. I hope it won't take me too much time. As soon as I add the branch to the test, I'll let you know so you can test it😉

**Comment by funmolde** [comment]
> Hello again. Sorry for taking so long to respond to your suggestion. I was busy with important parts of the project and simultaneously studying what you suggested. I think I'll be able to add DiffSinger. I hope it won't take me too much time. As soon as I add the branch to the test, I'll let you know so you can test it😉

Hello 😀 , take your time, let me know when you're done. 😉
Thank You
